# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'IBM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IBM
  pod 'SwiftyJSON', '~> 4.0' #handle network requests
  pod 'Alamofire', '~> 5.0' #for network requests


  target 'IBMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IBMUITests' do
    # Pods for testing
  end

end
